name: CI

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.13.0
    - name: yarn install
      run: yarn install
    - name: run lint
      run: yarn run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.13.0
    - name: yarn install
      run: yarn install
    - name: run lint
      run: yarn run test